language: rust
sudo: false
rust:
  - 1.24.1
  - stable
  - beta
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo run -p ci
  - cargo run --example default
  - if [ "${TRAVIS_RUST_VERSION}" = nightly ]; then cargo update -Z minimal-versions; fi
  - if [ "${TRAVIS_RUST_VERSION}" = nightly ]; then cargo run -p ci; fi
  - if [ "${TRAVIS_RUST_VERSION}" = nightly ]; then cargo run --example default; fi
after_success:
  - travis-cargo --only nightly doc-upload

notifications:
  email:
on_success: never
